---
title: "4050 HW1: Data Wrangling"
author: "Cameron Diwa"
date: "11/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

scorecard.dictionary <- read_csv("CollegeScorecardDataDictionary-09-12-2015.csv")
glimpse(scorecard.dictionary)
scorecard <- read_csv("CollegeScorecard.csv")
glimpse(scorecard)
crimes <- read_csv("Crime_2015.csv")
```

```{r}
statecrimerate <- crimes %>%
  group_by(State) %>%
  summarize(crimerate = sum(ViolentCrime + Murder + Rape + Robbery + AggravatedAssault + PropertyCrime + Burglary + Theft + MotorVehicleTheft, na.rm = TRUE)) # computes overall crime rate in each state, including Puerto Rico.

scorecard.filtered <- scorecard %>%
  mutate(State = STABBR) %>% # renames STABBR column to "State"
  select(INSTNM, CITY, State, ADM_RATE, UGDS_BLACK, UGDS_HISP, UGDS_ASIAN, UGDS_AIAN, UGDS_NHPI, UGDS_2MOR, UGDS_NRA, UGDS_UNKN, UGDS_WHITE, INC_PCT_LO, INC_PCT_M1, INC_PCT_M2, INC_PCT_H1, INC_PCT_H2, RET_FT4, PAR_ED_PCT_1STGEN, DEBT_MDN, C150_4) %>% # selects the selected columns
  filter(`CITY` == "Los Angeles" | `CITY` == "San Francisco" | `CITY` == "New York" | `CITY` == "Chicago" | `CITY` == "Seattle" | `CITY` == "Philadelphia") %>% # prints the rows that satisfy the filter
  mutate(pct_poc = (UGDS_BLACK + UGDS_HISP + UGDS_ASIAN + UGDS_AIAN + UGDS_NHPI + UGDS_2MOR) / (UGDS_BLACK + UGDS_HISP + UGDS_ASIAN + UGDS_AIAN + UGDS_NHPI + UGDS_2MOR + UGDS_NRA + UGDS_UNKN + UGDS_WHITE)) # computes the percent of the POC undergraduate population
```

```{r}
full.list <- full_join(scorecard.filtered, statecrimerate, by = "State") # joins the crime rate dataset to the scorecard.filtered dataset

list.diversity <- full.list %>%
  select(INSTNM, CITY, State, ADM_RATE, INC_PCT_LO, RET_FT4, pct_poc, PAR_ED_PCT_1STGEN, DEBT_MDN, C150_4, crimerate) %>%
  filter(INC_PCT_LO >= 0.3 & INC_PCT_LO != "PrivacySuppressed" & PAR_ED_PCT_1STGEN >= 0.2 & PAR_ED_PCT_1STGEN != "PrivacySuppressed" & pct_poc >= 0.35) %>%
  na.omit()

list.quality <- full.list %>%
  select(INSTNM, CITY, State, ADM_RATE, INC_PCT_LO, RET_FT4, pct_poc, PAR_ED_PCT_1STGEN, DEBT_MDN, C150_4, crimerate) %>%
  filter(ADM_RATE <= 0.35 & RET_FT4 >= 0.7 & C150_4 >= 0.6) %>%
  na.omit()

list.meddebt <- full.list %>%
  select(INSTNM, CITY, State, ADM_RATE, INC_PCT_LO, RET_FT4, pct_poc, PAR_ED_PCT_1STGEN, DEBT_MDN, C150_4, crimerate) %>%
  filter(DEBT_MDN <= 15000 & DEBT_MDN != "PrivacySuppressed") %>%
  na.omit()
```




